config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :postings
  
  resources :conversations do
    resources :messages
  end

  get 'users/postings', to: 'users#show', as: 'show_user_posts'
  root to: 'postings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id

 def message_time
  created_at.strftime('%m/%d/%y at %l:%M %p')
 end

end

app/models/posting.rb
class Posting < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  validates :address, :title, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true, presence: true, length: { minimum: 2, maximum: 16 }
  has_many :postings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

       def configure_permitted_parameters
           devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
       end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end


  private
    def message_params
      params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /postings
  # GET /postings.json
  def index
    if params[:search]
      @postings = Posting.where('address LIKE ?', "%#{params[:search]}%")
    else
      @postings = Posting.all
    end
    
    @hash = Gmaps4rails.build_markers(@postings) do |posting, marker|
      marker.lat posting.latitude
      marker.lng posting.longitude
      marker.infowindow render_to_string(partial: "/postings/map_box", locals: { posting: posting })
    end
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)
    @posting.user_id = current_user.id

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, address: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, address: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :search, :start, :address, :num_beds, :num_baths, :end, :comment, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(current_user.id)
  end
end

app/views/conversations/index.html.erb
<div class="main-content">
  <div class=''>
   <h3>Mailbox</h3>
     <% @conversations.each do |conversation| %>
      <div class='card' style="height:50px;">
       <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <div style="float:left;">
          <%= link_to recipient.username,   conversation_messages_path(conversation)%>
        </div>
        <div style="float:right;">
          <%= time_ago_in_words(conversation.updated_at) %> ago
        </div>
      </div>
       <% end %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Cal Bnb</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "//maps.google.com/maps/api/js?key=AIzaSyD550c1hBVyJPPIrt81EKMnHbytZ_xnjus" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
</head>

<body>
  <header class="navbar navbar-default">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Cal Bnb", root_path %></div>
        <div class="nav navbar-form navbar-left form-group">
          <%= form_tag(postings_path, method: :get) do %>
            <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
          <%end%>
        </div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Submit Posting', new_posting_path %></li>
              <li><%= link_to 'Messages', conversations_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Postings', show_user_posts_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
          <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end -%>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info alert-dismissable") %>
    <% end %>

    <div id="content" class="center-block">
      <%= yield %>
    </div>
  </div>
</body>

</html>

app/views/messages/index.html.erb
<div class="container">
  <% if @over_ten %>
   <%= link_to 'Show Previous', '?m=all' %>
  <% end %>
  <div class='ui segment'>
   <% @messages.each do |message| %>
    <% if message.body %>
     <% user = User.find(message.user_id) %>
      <div style="clear: both;">
        <div style="float:left;"><strong><%= user.username %></strong></div>
        <div style="float:left;">
         <span class='glyphicon glyphicon-menu-right'></span>
          <%= message.body %>
        </div>
        <div style="float:right;">
          <small><%= message.message_time %></small>
        </div>
     </div>
   <% end %>
  <% end %>
  </div>
</div>

<footer class="footer">
  <%= form_for [@conversation, @message], html: {class: ''} do |f| %>
  <div class="container" style="clear:both;">
    <div class='form-group' style="float:left;padding-top:10px;">
      <%= f.text_field :body, class: 'form-control' %>
    </div>
    <%= f.text_field :user_id, value: current_user.id, type: 'hidden' %>
    <div style="float:left;padding-top:10px;padding-left:10px;">
      <%= f.submit 'Send', class: 'btn btn-md btn-primary' %>
    </div>
  </div>
  <% end %>
</footer>

app/views/postings/_form.html.erb
<div class="row-fluid">
  <h1>New Posting</h1>
  <%= form_with(model: posting, local: true) do |f| %>
    <% if posting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(posting.errors.count, "error") %> prohibited this posting from being saved:</h2>
        <ul>
        <% posting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :start %><br>
      <%= f.date_field :start, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label '# of beds' %><br>
      <%= f.number_field :num_beds, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :comment %><br>
      <%= f.text_area :comment, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :end %><br>
      <%= f.date_field :end, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label '# of baths' %><br>
      <%= f.number_field :num_baths, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :price %><br>
        <%= f.number_field :price, class: "form-control" %>
      </div>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>

</div>

<% end %>

app/views/postings/_map_box.html.erb
<div class="map_box">
  <h3><%= posting.title %></h3>
  <p><%= posting.address %></p>
  <%= link_to "Details", posting_path(posting), target: :blank, class: "btn btn-warning" %>
</div>

app/views/postings/edit.html.erb
<div class="container">
  <h1>Editing Posting</h1>

  <%= render 'form', posting: @posting %>

  <%= link_to 'Show', @posting %> |
  <%= link_to 'Back', postings_path %>
</div>

app/views/postings/index.html.erb
<div class="row-fluid">
  <div class="col-md-6">
    <div id="mapa" style='width: 100%; height: 600px;'></div>
  </div>
  <div class="col-md-6">
    <% if @postings.blank? %>
      <h4>There are no postings containing the term <%= params[:search] %>.</h4>
    <%else%>

    <% @postings.each_slice(2) do |ps| %>
      <div class="row-fluid center-block">
        <% ps.each do |posting| %>
          <div class="card col-md-5">
            <div class="card-body">
              <% if user_signed_in? -%>
                <h4 class="card-title"><%= link_to posting.title, posting %></h4>
              <% else -%>
                <h4 class="card-title"><%= posting.title %></h4>
              <% end -%>
              <h6 class="mb-2 text-muted"><%= posting.address %></h6>
              <p class="card-text">$<%= posting.price %></p>
              <p class="card-text">Beds:<%= posting.num_beds %></p>
              <small class="author"><%= time_ago_in_words(posting.created_at).capitalize %>  ago by <%= posting.user.username %></small>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'mapa' } }, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();

    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
</script>

app/views/postings/new.html.erb
<div class="container">
  <%= render 'form', posting: @posting %>

  <%= link_to 'Back', postings_path %>
</div>

app/views/postings/show.html.erb
<div class="row-fluid">
  <div class="col-md-6">
    <div id="map_show" style='width: 100%; height: 600px;'></div>
  </div>
  <div class="col-md-6">
    <div class="card" style="height:200px;">
      <div class="card-body" style="clear:both;">
        <h4 class="card-title"><%= @posting.title %></h4>
        <h6 class="mb-2 text-muted"><%= @posting.address %></h6>
        <div class="col-md-5" style="padding:0px;">
          <p class="card-text">$<%= @posting.price %></p>
          <p class="card-text">Beds:<%= @posting.num_beds %></p>
        </div>
        <div class="col-md-5" style="padding:0px;">
          <p class="card-text">From<%= @posting.start %> to <%= @posting.start %></p>
          <p class="card-text">Baths:<%= @posting.num_baths %></p>
        </div>
        <p class="col-md-12 card-text" style="padding:0px;"><%= @posting.comment %></p>
        <small class="author col-md-12" style="padding:0px;">Submitted <%= time_ago_in_words(@posting.created_at) %>  ago by <%= @posting.user.username %></small>
      </div>
    </div>

    <% if @posting.user == current_user -%>
      <div class="btn-group">
        <%= link_to 'Edit', edit_posting_path(@posting), class: "btn btn-default" %>
        <%= link_to 'Destroy', @posting, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
      </div>
    <% else %>
      <div class="btn-group">
        <%= link_to 'Message!', conversations_path(sender_id: current_user.id, recipient_id: @posting.user.id), method: 'post', class: "btn btn-default"%>
      </div>
    <% end %>

  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'map_show' } }, function(){
    markers = handler.addMarkers([
      {
        "lat": <%=@posting.latitude%>,
        "lng": <%=@posting.longitude%>
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(16);
  });
</script>

app/views/users/show.html.erb
<div class="container">
  <h3>My Postings</h3>
  <% @user.postings.each_slice(3) do |ps| %>
    <div class="row">
      <% ps.each do |posting| %>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><%= link_to posting.title, posting %></h4>
            <h6 class="mb-2 text-muted"><%= posting.address %></h6>
            <div class="col-md-5" style="padding:0px;">
              <p class="card-text">$<%= posting.price %></p>
              <p class="card-text">Beds:<%= posting.num_beds %></p>
            </div>
            <div class="col-md-5" style="padding:0px;">
              <p class="card-text">From<%= posting.start %> to <%= posting.start %></p>
              <p class="card-text">Baths:<%= posting.num_baths %></p>
            </div>
            <p class="col-md-12 card-text" style="padding:0px;"><%= posting.comment %></p>
            <small class="author col-md-12" style="padding:0px;">Submitted <%= time_ago_in_words(posting.created_at) %>  ago</small>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>